resolver: nightly-2016-08-30

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - ansigraph-0.3.0.1


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
